news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('news/<int:pk>/', views.detail_news, name='detail_news'), 
    path('category/<int:id>/', views.news_by_category, name='news_by_category'),
    path('news/category/<int:id>/', views.news_by_category, name='news_by_category'),
] 

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from workspace import views as workspace_views
from news import views as news_views


urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('news.urls')),   
    path('auth/login/', workspace_views.login_profile, name='login'),
    path('auth/logout/', workspace_views.logout_profile, name='logout'),
    path('auth/register/', workspace_views.register, name='register'),
    path('auth/change-profile/', workspace_views.change_profile, name='change_profile'),
    path('auth/change-password/', workspace_views.change_password, name='change_password'),
    path('workspace/', include('workspace.urls')),
    path('', news_views.main, name='main')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

workspace/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.workspace, name='workspace'),
    path('news/', views.workspace),
    path('news/<int:id>/update/', views.update_news, name='update_news'),
    path('news/<int:id>/delete/', views.delete_news, name='delete_news'),
    path('news/create/', views.create_news, name='create_news'),
]

news/models.py
from django.db import models

class Product(models.Model):

    class Meta:
        verbose_name = 'протукт'
        verbose_name_plural = 'продукты'

    title = models.CharField(max_length=100, verbose_name='заголовок')
    price = models.FloatField(verbose_name='цена')
    image = models.ImageField(verbose_name = 'изображение', upload_to='news_images/', null=True)
    content = models.TextField(verbose_name='контент')
    category = models.ForeignKey('news.Category', on_delete=models.PROTECT, related_name='product', verbose_name='категория')
    tags = models.ManyToManyField('news.Tag', related_name='product', verbose_name='теги', blank=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='автор')

    def __str__(self):
        return f'{self.title}'
    
    
class Category(models.Model):

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    name = models.CharField(verbose_name='название', max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'
    

class Tag(models.Model):

    class Meta:
        verbose_name = 'тег'
        verbose_name_plural = 'теги'

    name = models.CharField(verbose_name='название', max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'


class ProductAttribute(models.Model):

    class Meta:
        verbose_name = 'атрибут новости'
        verbose_name_plural = 'атрибуты новостей'

    name = models.CharField(verbose_name='название', max_length=100)
    value = models.CharField(verbose_name='значение', max_length=100)
    product = models.ForeignKey('news.Product', on_delete=models.CASCADE, related_name='attributes', verbose_name='новость')

    def __str__(self):
        return f'{self.name} - {self.value}'


    
# class ProductImage(models.Model):
#
#     class Meta:
#         verbose_name = 'изображение продукта'
#         verbose_name_plural = 'изображения продуктов'
#
#     product = models.ForeignKey('Product', related_name='images', on_delete=models.CASCADE , verbose_name='продукты')
#     image = models.ImageField(verbose_name='изображения', upload_to='news_images/')

workspace/forms.py
from django import forms
from news.models import Product, Category, Tag

from django.contrib.auth.forms import BaseUserCreationForm
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.models import User


class ProductForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = 'Выберите категорию'

    class Meta:
        model = Product
        fields = [
            'title',
            'price',
            'image',
            'content',
            'category',
            'tags'
        ]

        widgets = {
            'title': forms.TextInput(
                attrs={'class': 'p-2 border rounded-lg w-full', 'placeholder': 'Введите заголовок'}),
            'price': forms.NumberInput(attrs={'class': 'p-2 border rounded-lg w-full', 'placeholder': 'Введите цену'}),
            'image': forms.FileInput(attrs={'accept': 'image/*', 'class': 'p-2 mt-7 w-full'}),
            'content': forms.Textarea(attrs={'class': 'p-2 border rounded-lg w-full', 'placeholder': 'Контент'}),
            'category': forms.Select(attrs={'class': 'p-2 border rounded-lg w-full'}),
            'tags': forms.CheckboxSelectMultiple(attrs={'class': 'p-2 border rounded-lg w-full'})
        }


class LoginForm(forms.Form):
    username = forms.CharField(label='Имя пользователя',
                               widget=forms.TextInput(
                                   attrs={'class': 'w-full border border-gray-300 rounded-3xl px-4 py-2 mb-4',
                                          'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(
        attrs={'class': 'w-full border border-gray-300 rounded-3xl px-4 py-2', 'placeholder': 'Введите пароль'}))


class RegisterForm(BaseUserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({
            'class': 'w-full border border-gray-300 rounded-3xl px-4 py-2 mb-4',
            'placeholder': 'Придумайте пароль'
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'w-full border border-gray-300 rounded-3xl px-4 py-2',
            'placeholder': 'Подтвердите пароль'
        })

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        )

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'w-full border border-gray-300 rounded-3xl px-4 py-2 mb-4',
                                                 'placeholder': 'Введите имя'}),
            'last_name': forms.TextInput(attrs={'class': 'w-full border border-gray-300 rounded-3xl px-4 py-2 mb-4',
                                                'placeholder': 'Введите фамилию'}),
            'username': forms.TextInput(attrs={'class': 'w-full border border-gray-300 rounded-3xl px-4 py-2 mb-4',
                                               'placeholder': 'Придумайте имя пользователя'}),
            'email': forms.EmailInput(attrs={'class': 'w-full border border-gray-300 rounded-3xl px-4 py-2 mb-4',
                                             'placeholder': 'Введите эл. почту'}),
        }


class ChangeProfileForm(forms.ModelForm):

    # email = forms.EmailField(label='Эл. почта', required=True,
    #                          widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Введите эл. почту'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
        )

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'w-full border border-gray-300 rounded-3xl px-4 py-2 mt-2',
                                                 'placeholder': 'Введите имя'}),
            'last_name': forms.TextInput(attrs={'class': 'w-full border border-gray-300 rounded-3xl px-4 py-2 mt-2',
                                                'placeholder': 'Введите фамилию'}),
            'username': forms.TextInput(attrs={'class': 'w-full border border-gray-300 rounded-3xl px-4 py-2 mt-2',
                                               'placeholder': 'Имя пользователя'}),
            'email': forms.EmailInput(attrs={'class': 'w-full border border-gray-300 rounded-3xl px-4 py-2 mt-2',
                                             'placeholder': 'Введите эл. почту'}),
        }


class ChangePasswordForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    password = forms.CharField(label='Текущий пароль',
                               widget=forms.PasswordInput(attrs={
                                   'class': 'w-full border border-gray-300 rounded-md px-4 py-2 mb-4 focus:border-blue-500',
                                   'placeholder': 'Введите текущий пароль'}))
    new_password = forms.CharField(label='Новый пароль',
                                   widget=forms.PasswordInput(attrs={
                                       'class': 'w-full border border-gray-300 rounded-md px-4 py-2 mb-4 focus:border-blue-500',
                                       'placeholder': 'Введите новый пароль'}),
                                   validators=[validate_password])
    confirm_password = forms.CharField(label='Подтвердите пароль',
                                       widget=forms.PasswordInput(attrs={
                                           'class': 'w-full border border-gray-300 rounded-md px-4 py-2 mb-4 focus:border-blue-500',
                                           'placeholder': 'Подтвердите пароль'}))

    def clean(self):
        data = self.cleaned_data

        password = data.get('password')
        new_password = data.get('new_password')
        confirm_password = data.get('confirm_password')

        errors = {}

        if not self.user.check_password(password):
            errors['password'] = ['Неправильный пароль']

        if new_password != confirm_password:
            errors['confirm_password'] = ['Пароли не совпадают']

        if len(errors) > 0:
            raise forms.ValidationError(errors)

        return data

workspace/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from news.models import Product, Category, Tag
from workspace.forms import ProductForm, LoginForm, RegisterForm, ChangeProfileForm, ChangePasswordForm
from django.contrib.auth import authenticate, login, logout
from workspace.decorators import login_required, own_news
from news.filters import ProductFilter
from django.db.models import Q
from django.contrib.auth.hashers import make_password


@login_required(login_url='/auth/login/')
def workspace(request):
    news = Product.objects.filter(author=request.user).order_by('title')

    search = request.GET.get('search')

    if search:
        news = news.filter(
            Q(title__icontains=search) |
            Q(category__name__icontains=search)
        )

    filter_set = ProductFilter(request.GET, queryset=news)
    paginator = Paginator(filter_set.qs, 6)
    page = int(request.GET.get('page', 1))
    news = paginator.get_page(page)

    return render(request, 'workspace/index.html', {'news': news, 'filter': filter_set})


@login_required()
def create_news(request):
    form = ProductForm()

    if request.method == 'POST':
        form = ProductForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            news = form.save(commit=False)
            news.author = request.user
            news.save()
            messages.success(request, f'Продукт "{news.title}" успешно создан!')
            return redirect('/workspace/')
        messages.error(request, f'Исправьте ошибки ниже')

    return render(request, 'workspace/create_news.html', {'form': form})


@login_required()
@own_news
def update_news(request, id):
    news = Product.objects.get(id=id)
    form = ProductForm(instance=news)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=news)
        if form.is_valid():
            form.save()
            messages.success(request, f'Продукт "{news.title}" успешно изменен!')
            return redirect('/workspace/')
        messages.error(request, f'Исправьте ошибки ниже')

    return render(request, 'workspace/update_news.html', {'form': form, 'news': news})


@login_required()
@own_news
def delete_news(request, id):
    news = get_object_or_404(Product, id=id)
    name = news.title
    news.delete()
    messages.success(request, f'Продукт "{name}" успешно удален!')
    return redirect('/workspace/')


def login_profile(request):
    if request.user.is_authenticated:
        return redirect('/')

    form = LoginForm()
    message = None

    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                messages.success(request,
                                 f'Добро пожаловать в рабочее пространство "{user.first_name} {user.last_name}"')
                return redirect('/workspace/')

            else:
                messages.error(request, f'Пользователь не существует или пароль неверен')

    return render(request, 'auth/login.html', {'form': form, 'message': message})


def logout_profile(request):
    if request.user.is_authenticated:
        logout(request)

    return redirect('/')


def register(request):
    if request.user.is_authenticated:
        return redirect('/')

    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, f'Добро пожаловать в рабочее пространство "{user.first_name} {user.last_name}"')
            return redirect('/workspace/')

        messages.error(request, f'Исправьте ошибки ниже')

    return render(request, 'auth/register.html', {'form': form})


@login_required()
def change_profile(request):
    form = ChangeProfileForm(instance=request.user)

    if request.method == 'POST':
        form = ChangeProfileForm(instance=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Ваш профиль успешно изменен!')
            return redirect('/workspace/')

        messages.error(request, f'Исправьте ошибки ниже')

    return render(request, 'auth/change_profile.html', {'form': form})


@login_required()
def change_password(request):
    form = ChangePasswordForm()

    if request.method == 'POST':
        form = ChangePasswordForm(data=request.POST, user=request.user)
        if form.is_valid():
            new_password = form.cleaned_data.get('new_password')
            user = request.user
            # user.password = make_password(new_password)
            user.set_password(new_password)
            user.save()

            login(request, user)

            messages.success(request, f'Ваш пароль был изменен!')
            return redirect('/workspace/')

        messages.error(request, f'Ваш пароль не верный или не совподает')

    return render(request, 'auth/change_password.html', {'form': form})

templates/workspace/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Нотубуки {% block title %}{% endblock title %}</title>
</head>

<body>
    
    {% include 'components/nav.html' %}
    
    <div class="container">
        {% include 'components/messages.html' %}
        {% block content %}{% endblock content %}
    </div>

</body>

</html>

templates/workspace/create_news.html
{% extends 'workspace/base.html' %}

{% block title %}| Создание ноутбука {% endblock title %}
{% load static %}
{% block content %}

    <section class="card-create rounded-lg">
        <form action="{% url 'create_news' %}" method="post" novalidate enctype="multipart/form-data">
            {% csrf_token %}
                <h2 class="h2 mb-10 mt-4 text-black text-center text-2xl font-bold">Добавление ноутбука</h2>
                <div class="flex2 flex justify-between gap-10">
                    <div class="mb-2 price-inpt w-full">
                        <label for="id_title">{{ form.title.label }}</label>
                        {{ form.title }}
                        {% for error in form.title.errors %}
                            <div class="mt-1 mb-2 text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-2 price-inpt w-full">
                        <label for="id_price">{{ form.price.label }}</label>
                        {{ form.price }}
                        {% for error in form.price.errors %}
                            <div class="mt-1 mb-2 text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>

                <div class="flex2 flex justify-between items-center mt-5 gap-10">
                    <div class="img mt-2 relative rounded-md shadow-sm price-inpt price-inpt2">
                        <input id="id_image" name="image" type="file" class="form-control hidden">
                        <label for="id_image">
                            <div class="mb-2 border-dashed border-2 border-slate-800 flex flex-col justify-center items-center cursor-pointer">
                                <img src="{% static 'admin/download_image.svg' %}" alt="" class="w-24 h-48">
                            </div>
                            <span class="cursor-pointer py-2 px-4 block bg-black text-center bg-slate-800 text-white rounded-md hover:bg-slate-900 focus:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                 Выбрать файл
                                </span>
                        </label>
                        {% for error in form.image.errors %}
                            <div class="mt-1 mb-2 text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-2">
                        <label for="id_content">{{ form.content.label }}</label>
                        {{ form.content }}
                        {% for error in form.content.errors %}
                            <div class="mt-1 mb-2 text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
                <div class="mb-2">
                    {{ form.category }}
                    {% for error in form.category.errors %}
                        <div class="mt-1 mb-2 text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="mb-2">
                    <label for="id_tags" class="mr-2">{{ form.tags.label }}</label>
                    {{ form.tags }}
                    {% for error in form.tags.errors %}
                        <div class="mt-1 mb-2 text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <button type="submit" class="btn-login rounded-lg">Добавить</button>
        </form>
    </section>

    <style>
        body {
            background-image: url("/media/создать.jpeg");
            background-size: cover;
            background-position: center;
            max-width: 2000px;
            width: 100%;
        }

        .card-create {
            background-color: white;
            padding: 25px 30px;
            margin: 40px auto;
            max-width: 800px;
            width: 100%;
        }

        input {
            width: 100%;
            border: 1px solid gray;
            padding: 5px 8px;
        }

        input:hover {
            outline: none;
            border-color: #4CAF50;
        }

        input:focus {
            outline: none;
            border-color: #4CAF50;
        }

        .price-inpt {
            width: 350px;
        }

        .price-inpt2 {
            width: 440px;
        }

        .btn-login {
            background-color: #4CAF50;
            color: white;
            padding: 10px 15px;
            font-size: 1.2rem;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            margin-top: 10px;
            width: 100%;
        }

        .btn-login:hover {
            background-color: #45a049;
        }

        .text-danger {
            color: #dc3545;
            font-size: 1rem;
            margin-top: 0.5rem;
        }

        @media (max-width: 1050px) {
            .card-create {
                padding: 25px 30px;
                margin: 40px auto;
                max-width: 700px;
                width: 100%;
            }

            .btn-login {
                padding: 8px 13px;
                font-size: 1.1rem;
                transition: background-color 0.3s ease;
            }
        }

        @media (max-width: 750px) {

            .card-create {
                padding: 25px 30px;
                margin: 40px auto;
                max-width: 600px;
                width: 100%;
            }

            .btn-login {
                padding: 10px 10px;
                font-size: 1.0rem;
                transition: background-color 0.3s ease;
                margin-top: 10px;
            }
        }

        @media (max-width: 650px) {

            .card-create {
                padding: 25px 30px;
                margin: 40px auto;
                max-width: 500px;
                width: 100%;
            }

            .flex2 {
                flex-direction: column;
                width: 100%;
            }

            .price-inpt {
                width: 100%;
            }

            .btn-login {
                padding: 10px 10px;
                font-size: 1.0rem;
                transition: background-color 0.3s ease;
                margin-top: 10px;
            }
        }

        @media (max-width: 650px) {
            .h2 {
                font-size: 22px;
            }

            .img {
                width: 100%;
            }
        }
    </style>

{% endblock content %}

templates/workspace/update_news.html
{% extends 'workspace/base.html' %}

{% block title %}| Изменение ноутбука {% endblock title %}
{% load static %}
{% block content %}

    <section class="card-create rounded-lg">
        <form action="{% url 'update_news' news.id %}" method="post" novalidate enctype="multipart/form-data">
            {% csrf_token %}
                <h2 class="h2 mb-10 mt-4 text-black text-center text-2xl font-bold">Изменение ноутбука</h2>
                <div class="flex2 flex justify-between gap-10">
                    <div class="mb-2 price-inpt w-full">
                        <label for="id_title">{{ form.title.label }}</label>
                        {{ form.title }}
                        {% for error in form.title.errors %}
                            <div class="mt-1 mb-2 text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-2 price-inpt w-full">
                        <label for="id_price">{{ form.price.label }}</label>
                        {{ form.price }}
                        {% for error in form.price.errors %}
                            <div class="mt-1 mb-2 text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>

                <div class="flex2 flex justify-between items-center mt-5 gap-10">
                    <div class="img mt-2 relative rounded-md shadow-sm price-inpt price-inpt2">
                        <input id="id_image" name="image" type="file" class="form-control hidden">
                        <label for="id_image" class="">
                            <div class="mb-2 border-dashed border-2 border-slate-800 flex flex-col justify-center items-center cursor-pointer">
                                <img src="{% static 'admin/download_image.svg' %}" alt="" class="w-24 h-48">
                            </div>
                            <span class="cursor-pointer py-2 px-4 block bg-black text-center bg-slate-800 text-white rounded-md hover:bg-slate-900 focus:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                 Выбрать файл
                                </span>
                        </label>
                        {% for error in form.image.errors %}
                            <div class="mt-1 mb-2 text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-2">
                        <label for="id_content">{{ form.content.label }}</label>
                        {{ form.content }}
                        {% for error in form.content.errors %}
                            <div class="mt-1 mb-2 text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
                <div class="mb-2">
                    {{ form.category }}
                    {% for error in form.category.errors %}
                        <div class="mt-1 mb-2 text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="mb-2">
                    <label for="id_tags" class="mr-2">{{ form.tags.label }}</label>
                    {{ form.tags }}
                    {% for error in form.tags.errors %}
                        <div class="mt-1 mb-2 text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
                <button type="submit" class="btn-login rounded-lg w-full">Сохранить</button>
        </form>
    </section>

    <style>
        body {
            background-image: url("/media/создать.jpeg");
            background-size: cover;
            background-position: center;
            max-width: 2000px;
            width: 100%;
        }

        .card-create {
            background-color: white;
            padding: 25px 30px;
            margin: 40px auto;
            max-width: 800px;
            width: 100%;
        }

        input {
            width: 100%;
            border: 1px solid gray;
            border-radius: 5px;
            padding: 5px 8px;
        }

        input:hover {
            outline: none;
            border-color: #4CAF50;
        }

        input:focus {
            outline: none;
            border-color: #4CAF50;
        }

        .price-inpt {
            width: 350px;
        }

        .price-inpt2 {
            width: 440px;
        }

        .btn-login {
            background-color: #4CAF50;
            color: white;
            padding: 10px 15px;
            font-size: 1.2rem;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            margin-top: 10px;
        }

        .btn-login:hover {
            background-color: #45a049;
        }

        .text-danger {
            color: #dc3545;
            font-size: 1rem;
            margin-top: 0.5rem;
        }

        @media (max-width: 1050px) {
            .card-create {
                padding: 25px 30px;
                margin: 40px auto;
                max-width: 700px;
                width: 100%;
            }

            .btn-login {
                padding: 8px 13px;
                font-size: 1.1rem;
                transition: background-color 0.3s ease;
            }
        }

        @media (max-width: 750px) {

            .card-create {
                padding: 25px 30px;
                margin: 40px auto;
                max-width: 600px;
                width: 100%;
            }

            .btn-login {
                padding: 10px 10px;
                font-size: 1.0rem;
                transition: background-color 0.3s ease;
                margin-top: 10px;
            }
        }

        @media (max-width: 650px) {

            .card-create {
                padding: 25px 30px;
                margin: 40px auto;
                max-width: 500px;
                width: 100%;
            }
            
            .flex2{
                flex-direction: column;
                width: 100%;
            }
            
            .price-inpt{
                width: 100%;
            }

            .btn-login {
                padding: 10px 10px;
                font-size: 1.0rem;
                transition: background-color 0.3s ease;
                margin-top: 10px;
            }
        }
        
        @media (max-width: 650px) {
            .h2{
                font-size: 22px;
            }
            
            .img{
                width: 100%;
            }
        }
    </style>

{% endblock content %}